
adjective = input("Adjective: ")
adjective2 = input("Adjective: ")
bird = input("Type of bird: ")
room = input("Room in a house: ")
verb = input("Past tense verb: ")
verb2 = input("Verb: ")
relative = input("Relative's name: ")
noun = input("Noun: ")
liquid = input("Type of liquid: ")
verb3 = input("Verb ending in -ing: ")
body = input("Part of the body-plural: ")
noun2 = input("Plural Noun: ")
verb4 = input("Verb ending in -ing: ")
noun3 = input("Noun: ")
print("It was a " + adjective + " , cold November day.")
print("I woke up to the " + adjective2 + " smell of " + bird + " roasting in the " + room + " downstairs.")
print("I " + verb + " down the stairs to see if I could help " + verb2 + " the dinner.")
print('My mom said, "See if "' + relative + ' needs a fresh' + noun + '."')
print("So I carried a tray of glasses full of " + liquid + " into the " + verb3 + " room.")
print("When I got there, I couldn't believe my " + body + "!")
print("There were " + noun2 + " " + verb4 + " on the " + noun3 + "!")
