noun1 = input("A thing:")
noun2 = input("Another thing:")
noun3 = input("A plural noun:")
verb1 = input("An action verb:")
noun4 = input("A famous occupation:")
verb2 = input("Another verb:")
noun5 = input("A noun for a group of people:")
verb3 = input("Another action verb:")
noun6 = input("A place:")
print("Mother, do you think they'll drop the " + (noun1) + "?")
print("Mother, do you think they'll like this " + (noun2) + "?")
print("Mother, do you think they'll try to break my " + (noun3) + "?")
print("OOh Ah")
print("Mother, should I build the " + (noun1) + "?")
print("Mother, should I " + (verb1) + " for" + (noun4) + "?")
print("Mother, should I " + (verb2) + " the" + (noun5) + "?")
print("Mother, will they " + (verb3) + " me in the" + (noun6) + "?")
